name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-app

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2
        extensions: mbstring, intl, pdo_sqlite
        coverage: none

    - name: Cache Composer
      uses: actions/cache@v4
      with:
        path: |
          ~/.composer/cache/files
          my-app/vendor
        key: ${{ runner.os }}-php83-${{ hashFiles('my-app/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php83-

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install dependencies
      run: composer install --no-interaction --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R ug+rwX storage bootstrap/cache

    - name: Execute tests
      run: php artisan test --no-interaction
